#! /usr/bin/env bash

# Author:  Thomas DEBESSE <dev@illwieckz.net>
# License: MIT

set -u -e -o pipefail

_help()
{
	cat >&2 <<-EOF
	USAGE: ${0} -s SIZE INFILE OUTFILE
	EOF
}

_message()
{
	topic="${1}"; shift
	format="${1}"; shift
	printf "%s: ${format}\n" "${topic}" "${@}" >&2
}

_error()
{
	_message 'ERROR' "${@}" || true
	printf '\n'
	_help
	false
}

_failure()
{
	_message 'FAILURE' "${@}"
	false
}

_main()
{
	case "${1:-}" in
		'-h'|'--help')
			_help
			exit
		;;
	esac

	if [ "${1:-}" != '-s' ]
	then
		_error 'First argument must be -s'
	fi

	if [ -z "${2:-}" ]
	then
		_error 'Second argument must be a number'
	else
		local SIZE="${2}"
	fi

	if [ -z "${3:-}" ]
	then
		_error 'Third argument must be the input file'
	else
		local INFILE="${3}"
	fi

	if [ ! -f "${INFILE}" ]
	then
		_error "File doesn't exist: %s" "${INFILE}"
	fi

	if [ -z "${4:-}" ]
	then
		_error 'Fourth argument must be the output file'
	else
		local OUTFILE="${4}"
	fi

	local name
	for name in 'gimp-console' 'gimp'
	do
		if command -v "${name}" >/dev/null 2>&1
		then
			local command="${name}"
			break
		fi
	done

	if [ -z "${command:-}" ]
	then
		_failure 'Missing GIMP binary: gimp-console or gimp'
	fi

	"${command}" --new-instance --no-interface --no-data \
		--batch "
			(let* (
					(image (car (gimp-file-load RUN-NONINTERACTIVE \"${INFILE}\" \"${INFILE}\")))
					(drawable (car (gimp-image-get-active-layer image)))
					(width (car (gimp-image-width image)))
					(height (car (gimp-image-height image)))
					(scale (/ ${SIZE} (max width height)))
					(new-width (round (* width scale)))
					(new-height (round (* height scale)))
					(drawable (car (gimp-image-merge-visible-layers image CLIP-TO-IMAGE)))
				)
				(gimp-image-scale image new-width new-height)
				(file-png-save RUN-NONINTERACTIVE image drawable \"${OUTFILE}\" \"${OUTFILE}\" 0 9 0 0 0 0 0)
				(gimp-image-delete image)
			)" \
		--batch "(gimp-quit 0)" \
		>/dev/null 2>&1
}

_main "${@}"
